### ISSUE TITLE
Table row styling bug

### ISSUE THREAD

**Issue by ivan-zynesis** [BirthdayResearch/defichain-wallet#1070]
![image](https://user-images.githubusercontent.com/44192990/137425277-9472a3ac-d52e-4ea0-94e6-9df51f441ed3.png)

#### What UI/UX improvements would you like to be implemented: 
- missing rounded corner for convert receive token box and and borderline
- Fix missing top border for all row

**Comment by ivan-zynesis** [comment]
@thedoublejay minor UI bug

**Comment by thedoublejay** [comment]
Thanks @ivan-zynesis 

Updated design (Should look the same in Dark Mode):

![image](https://user-images.githubusercontent.com/25013382/137441132-42d0dc06-d0b3-4bb1-9b87-a2d9bff2cb82.png)
