### ISSUE TITLE
`your liquidity` - update label

### ISSUE THREAD

**Issue by thedoublejay** [BirthdayResearch/defichain-wallet#1100]
#### What would you like to be added:
Update label for "Your Liquidity" to avoid confusion with normal liquidity. Needs design @jtlntno-cake

**Comment by jtlntno-cake** [comment]
Figma screen updated. Link seen [here](https://www.figma.com/file/SDIpZciuxJlUf4xf8yheiY/Mobile-Light-Wallet?node-id=1470%3A54060)

**Comment by izzycsy** [comment]
Acceptance Criteria: Updated design and labels for `Pool Pairs` 

Android: 
- [x] In `Browse pool pairs`, `+ Add liquidity` & `> < Swap tokens` present
- [x] In `Your pool pairs`, `+ Add more` & `- Remove` present

iOS: 
- [x] In `Browse pool pairs`, `+ Add liquidity` & `> < Swap tokens` present
- [x] In `Your pool pairs`, `+ Add more` & `- Remove` present
