### ISSUE TITLE
Fresh wallet adress with USDC-DFI invisible until first DFI arrives

### ISSUE THREAD

**Issue by benameless** [BirthdayResearch/defichain-wallet#1128]
#### What happened:
My DFI address is invisible on DeFiChain Explorer

#### What you expected to happen:
My DFI address was visible on DeFiChain Explorer

#### How to reproduce it (as minimally and precisely as possible):
I created a new wallet on "DeFiChain wallet mobile app" and had 0 coins on it. I transferred some USDC-DFI-tokens to it from "DeFi Wallet desktop app". The tokens arrived and generated DFI (Token) rewards. I still had 0 DFI (UTXO) on it.

#### Anything else we need to know?:
A mod from Telegram sent me 0,001 DFI to the address. After a couple of minutes the address was visible and worked. This means I had to have DFI (UTXO) on this wallet before it was visible.

**Comment by thedoublejay** [comment]
@benameless DeFiScan released their address page. You can try to search it from there - https://defiscan.live/address
