### ISSUE TITLE
French Text in German Lightwallet Version

### ISSUE THREAD

**Issue by Bobby-Sh** [BirthdayResearch/defichain-wallet#3443]
There is a French Message in the German Verson of Lightwallet. 
You can find it, if you add/remove Liquidity in the Liquidity Pools. 
![Screenshot_20220912-091535_DeFiChain Wallet](https://user-images.githubusercontent.com/113335857/189596402-7d32e1de-b3cb-4414-9552-20167c66c111.jpg)

**Comment by lykalabrada** [comment]
Hi @Bobby-Sh thanks for reporting the issue, this has been fixed on [PR-3378](https://github.com/DeFiCh/wallet/pull/3378) and will be included in the upcoming release
