### ISSUE TITLE
creating a DFIP fails

### ISSUE THREAD

**Issue by kuegi** [BirthdayResearch/defichain-wallet#3946]
Trying to create a DFIP in the LW fails with "malformed tx vouts (wrong creation fee) (code 16)"

The address has enough DFI and everything seems fine until the tx is sent to ocean. 

Just tried with another address: with 51 DFI UTXOs in the address, the wallet itself says "not enough DFI UTXOs" which is also wrong.

**Comment by MasternodeOwner** [comment]
Just testet the submission via light wallet:
1) Submitting on testnet was succesfull
![Screenshot_20230630_113421_com defichain app
(https://github.com/BirthdayResearch/defichain-wallet/assets/91147950/4d7d4ca9-8609-4a28-b78f-2692fe4a0dac)
2) Submitting on mainnet still fails though
![Screenshot_20230630_112700_com defichain app](https://github.com/BirthdayResearch/defichain-wallet/assets/91147950/f1631bcb-3683-4812-95a5-018fa4fbed2f)
![Screenshot_20230630_112549_com defichain app](https://github.com/BirthdayResearch/defichain-wallet/assets/91147950/7eda54de-8015-4c93-a2e0-e3bef19f2530)

**Comment by MasternodeOwner** [comment]
Just testet submitting of DFIP via LightWallet

1) Submitting on testnet was successfull
![Screenshot_20230630_113421_com defichain app](https://github.com/BirthdayResearch/defichain-wallet/assets/91147950/c2686ef6-7669-40b2-b486-2d3c8faf83b3)

2)Submitting on mainnet failed though. LightWallet was updated and just restarted.

![Screenshot_20230630_112700_com defichain app](https://github.com/BirthdayResearch/defichain-wallet/assets/91147950/df1d691f-97b2-4d7f-91b0-27e87bb15258)
![Screenshot_20230630_112549_com defichain app](https://github.com/BirthdayResearch/defichain-wallet/assets/91147950/9563c6cc-05f2-48ac-94a8-055f8cecc81d)
