### ISSUE TITLE
Allow DUSD loops in Vault in changi network

### ISSUE THREAD

**Issue by DeFiPages** [BirthdayResearch/defichain-wallet#4034]
#### What happened:
[DVM: Enable DUSD loops in vaults #1971](https://github.com/DeFiCh/ain/pull/1971) was integrated in June in a beta release for changi. Now I want test it in the Lightwallet with a new vault and DUSD as collateral. But the Lightwallet does not allow it: Continue Button is disabled with message: 'Insuffucient DFI in vault. Add more to borrow DUSD'

#### What you expected to happen:
Allow to borrow DUSD in a Vault with DUSD collateral.
#### How to reproduce it (as minimally and precisely as possible):
- Switch to changi network
- Create Vault
- Add DUSD as collateral
- try to borrow DUSD

**Comment by Krysh90** [comment]
It is still not possible with the new version 2.27.0. which already support EVM.
This is important and needs to be fixed!

**Comment by Krysh90** [comment]
Thanks for the info and sorry to be that resilient on this issue. We must make sure to have it in before the hardfork is done.

We must not make the same mistake again and keep out 95% of our community.

If there is any way, I can help in this regard. Let me know. Thanks for having this issue on the radar. I just want to point out and make sure that the prio for the community is in check
