### ISSUE TITLE
Not possible to mint dTokens since Update to Version 2.28.0

### ISSUE THREAD

**Issue by Kassius84** [BirthdayResearch/defichain-wallet#4128]
#### What happened:
Hey Dev team, are there any known problems with the latest version of the lightwallet and the minting of dTokens? There are corresponding messages in the English and German speaking telegram chat. Users receive an error message even though all requirements for DFI/dUSD are met.

#### What you expected to happen:
Minting of dTokens

**Comment by Krysh90** [comment]
Verified it just now. 
If you have a vault with only DUSD as collateral, it is not possible anymore to loan dToken. This should be possible and it was on 2.27.0.

**Comment by Krysh90** [comment]
affected version 2.28.0

**Comment by Kassius84** [comment]
Fixed
