### ISSUE TITLE
Issue for add a whitelisted address book Metachain EVM address.

### ISSUE THREAD

**Issue by angelocastiglione** [BirthdayResearch/defichain-wallet#4137]
Is not possible to add to my whitelisted address book Metachain EVM address.

I receive this error: please enter a valid address

I am using version 2.31.0. Wait a reply.

Thanks
Angelo Castiglione

![Screenshot 2023-11-20 (14 52 51)](https://github.com/BirthdayResearch/defichain-wallet/assets/82758166/7bb2c8e9-ea70-46ba-bf24-59494dd25a3c)

**Comment by pierregee** [comment]
Hello we just released the EVM feature a few mins ago. Restart your app and check again! thanks for raising!
