### ISSUE TITLE
EVM on LW does not show DUSD balance

### ISSUE THREAD

**Issue by flibflob13** [BirthdayResearch/defichain-wallet#4158]
#### What happened:

I transferred DUSD from the DVM to the EVM on the LW. While the transaction has gone through and I can see the correct balance on mydefichain, in the LW the DUSD do not show up at all. Meaning I can't use them at the moment.

#### What you expected to happen:
To see the correct balance in the LW.

#### How to reproduce it (as minimally and precisely as possible):
Send DUSD from the DVM to EVM on LW. Apparently there are cases in which it works and in which it doesn't.

**Comment by pierregee** [comment]
Did Light Wallet happen to give any error messages, and has the correct balance eventually appeared, or is it still showing an incorrect balance?

**Comment by flibflob13** [comment]
No, no error was shown and the balance remains incorrect. If I send DFI to the address, they are updated correctly though. The error only applies to DUSD balance.

**Comment by flibflob13** [comment]
After sending a smaller amount of DUSD from DVM to EVM it eventually did show the correct balance. However this should happen immediately.

**Comment by pierregee** [comment]
This has been fixed with the latest release. Please update and check, thanks!
