### ISSUE TITLE
Light Wallet EVM doesn't show USDC Balance

### ISSUE THREAD

**Issue by LastHour123** [BirthdayResearch/defichain-wallet#4160]
**#### What happened:** 
I transferred USDC from DMC MetaMask Wallet to EVM address on DefiChain LightWallet. The USDC arrived as per block explorer, I do not see them / cannot interact or send.

**#### What you expected to happen:** 
To be able to use USDC in Lightwallet.

**#### How to reproduce it (as minimally and precisely as possible):**
 Send USDC to Lightwallet on EVM.

**#### Anything else we need to know?:** 
Yesterday it worked.
DUSD show up. If I send them over to baselayer and convert them to USDC and send those back to EVM, they don't show up either.

**Comment by pierregee** [comment]
Has the correct balance eventually appeared, or is it still showing an incorrect balance?

**Comment by LastHour123** [comment]
> Has the correct balance eventually appeared, or is it still showing an incorrect balance?

Hey pierregee, thanks for reaching out! It's still showing no balance.

**Comment by RoMi1981** [comment]
This happens also for different token like usdt or dtoken. I think the main issue here is the evm balance endpoint which is not updated ordinary so the LW did not display the right balance.

A workaround is to send a small amount of the missing token from external address to evm address again or convert a small amount of the missing token from DVM to EVM.

**Comment by LastHour123** [comment]
> This happens also for different token like usdt or dtoken. I think the main issue here is the evm balance endpoint which is not updated ordinary so the LW did not display the right balance.
> 
> A workaround is to send a small amount of the missing token from external address to evm address again or convert a small amount of the missing token from DVM to EVM.

I tried it and it works now! Thank you very much
