### ISSUE TITLE
Adress book deletes adresses deletes after one transaction

### ISSUE THREAD

**Issue by flibflob13** [BirthdayResearch/defichain-wallet#4161]
#### What happened:
I saved an address in the LW address book and used it for a transaction afterwards. When accessing the address book again it is empty and no saved address is displayed.

#### What you expected to happen:
Address should be displayed in address book after transaction.

#### How to reproduce it (as minimally and precisely as possible):
Save an address in the LW and use it for a transaction afterwards.

**Comment by fullstackninja864** [comment]
Its fixed in https://github.com/BirthdayResearch/defichain-wallet/pull/4156, Please download latest version of app.
I'll now close this ticket. If you encounter any further issues, please don't hesitate to open a new ticket.
