### ISSUE TITLE
Add new Adresses in Light Wallet

### ISSUE THREAD

**Issue by Smolmarc** [BirthdayResearch/defichain-wallet#4165]
hey Community, I noticed that the button to add a new wallet address has been removed. at least in my view of the LightWallet. A friend still has the button. Please check once and if necessary fix this bug so that you can add addresses again. Thank you and best regards

**Comment by fullstackninja864** [comment]
@Smolmarc The 'Add New Address' button will only appear if there have been UTXO funds associated with the address. 
I'll now close this ticket. If you encounter any further issues, please don't hesitate to open a new ticket.
