### ISSUE TITLE
Can not set slipage above 100%

### ISSUE THREAD

**Issue by kuegi** [BirthdayResearch/defichain-wallet#4170]
With the upcoming fee change (up to 80% fee on DUSD sells), the current LW behaviour will prevent any DUSD->crypto swaps.

The slipage in the LW is used as `maxPrice= expectedPrice*(1+slipage)`. Since the fee is removed before the swap even happens, a 80% fee means the resulting price is 400% worse in the above definition (1/(1-0.8) = 5).

Unfortunately the LW only allows to enter a slipage between 0 and 100%. So any fee above 50% leads to LW users no longer being able to swap.

**Comment by fullstackninja864** [comment]
Hi @kuegi , Current range for custom input in LW is 0-100% (more than zero). What range you are suggesting to get this issue fixed?

**Comment by kuegi** [comment]
> Hi @kuegi , Current range for custom input in LW is 0-100% (more than zero). What range you are suggesting to get this issue fixed?

do you have to set an upper limit? for it to work with the 80% fee, it needs to be set > 400%.
