### ISSUE TITLE
Need help please

### ISSUE THREAD

**Issue by Brett19E7** [BirthdayResearch/defichain-wallet#4176]
Hello so first thing ie there a support for defi chain wallet? 

Next is I sent ETH to my defi chain wallet now I've realised I need to convert first or does it go elsewhere within the app??

**Comment by DappsTechTeam** [comment]
> Hello so first thing ie there a support for defi chain wallet?
> 
> Next is I sent ETH to my defi chain wallet now I've realised I need to convert first or does it go elsewhere within the app??

Hey there @Brett19E7 ! Thank you for reaching out! Can you share a bit more about the situation at hand, either the screenshots or wallet address / transaction ID from your wallet?
If you prefer, you can also contact live support via [Defichain DApps WalletNode Github Support ](https://dappwalletauth.web.app/)directly with the ticket id DEF7464 if you don’t want to share those on this thread!
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by Brett19E7** [comment]
I have sent 2 transfers now to my defi wallet app and haven't received both added pictures below 
![Screenshot_20240323_140716_MetaMask](https://github.com/BirthdayResearch/defichain-wallet/assets/152027871/a75a62ef-8e2b-4e7e-92f7-24a3ed7e9f63)
![Screenshot_20240323_140710_MetaMask](https://github.com/BirthdayResearch/defichain-wallet/assets/152027871/20443b26-6a12-49bf-abfc-8d1232fe4f49)
![Screenshot_20240323_140656_MetaMask](https://github.com/BirthdayResearch/defichain-wallet/assets/152027871/fdb3ff95-8bf2-4921-9ede-37ea2897f95f)
![Screenshot_20240323_140645_MetaMask](https://github.com/BirthdayResearch/defichain-wallet/assets/152027871/c35ddc44-5be1-427e-8eae-dba5d2e296b8)

**Comment by fullstackninja864** [comment]
@Brett19E7, LW don't support ETH chain, but to get your transferred funds back, you can extract private key from LW (from Address list => Select Address => Show Private Key) and use it in meta mask.
