### ISSUE TITLE
Bug after update today

### ISSUE THREAD

**Issue by Smolmarc** [BirthdayResearch/defichain-wallet#4180]

**Comment by pierregee** [comment]
@Smolmarc could you provide more details on the issue you are facing:
1. Light Wallet version
2. What device are you using?

We have tried the issue you that you mentioned but we can't seem to replicate it as it all works for us:
1. Borrow button is working on our end
2. Swap button doesn't seem hidden. Can you provide a screenshot?
3. Changing address also works on our end

**Comment by Smolmarc** [comment]
1. I have made an update yesterday by the Version 2.40.0
2. I use an Samsung S21fe
    Since yesterday after the update everything runs perfekt
3. On tablet or other Smartphones the Light wallet is running without Bugs.

I sent you a little Video within These Mail, to Show what happend.


Pierre Gee ***@***.***> schrieb am Mi., 3. Apr. 2024, 04:13:

**Comment by edgeball** [comment]
same here. 
Iphone 13 Pro
iOS: 17.4.1
Light Wallet: 2.41.0

Ever since the latest update (2.41.0) the pin request doen't pop up. I can't make any transactions

**Comment by Smolmarc** [comment]
the problem is still there. Is there any information on how and when it will be fixed? Unfortunately, no transactions can still be implemented.

**Comment by ojbcrypto** [comment]
Same here:
IPhone X
iOS: 16.4.1
Light Wallet: 2.41.0
I wanted to send DFI to the DMC but the PIN doesn't appear after pressing the continue button.

**Comment by pierregee** [comment]
Please provide screenshots of the issues to help the team in debugging the issue

**Comment by Smolmarc** [comment]
Within these Mail, i sent you a Clip


Pierre Gee ***@***.***> schrieb am Do., 11. Apr. 2024, 03:19:

**Comment by supervolot** [comment]
Same bug:
I PHone 13
iOS: 17.4.1
Ligth Wallet: 2.41.0
the PIN doesn't appear after pressing the continue button

**Comment by supervolot** [comment]
> Please provide screenshots of the issues to help the team in debugging the issue

It looks like the version 2.41.0 has a bug so please just put the last version on the appstore that was working. When the app runs fine again you can check that bug
THX

**Comment by edgeball** [comment]
> Please provide screenshots of the issues to help the team in debugging the issue

the fact that nothing is happening after pressing "Swap", a screenshot can therefore not show you much

**Comment by FVB95** [comment]
Hello, the bug is now here for two weeks an nothing happend. The LW does also for me not working and has the same problems as described. I also have an iPhone 13 Pro and the newest Version. Thanks for helping!

**Comment by pierregee** [comment]
Please test with version 2.42.0 and inform us if the problem persists.

Users experiencing issues likely have Reduce Motion enabled in their iOS settings, preventing the bottom sheet component from appearing.

To address this, we've implemented a fix that disables the animation of the bottom sheet when Reduce Motion is enabled. If Reduce Motion is disabled, the app will function normally.

**Comment by FVB95** [comment]
Thanks for the update. Now it works. Awesome 👍🏻👍🏻

**Comment by supervolot** [comment]
At the Apple Store the 2.42. version is not online ?

**Comment by edgeball** [comment]
Yes, I can confirm. It works again on iPhone 13 Pro. IOS 17.4.1

Thank you
