### ISSUE TITLE
`restore wallet` - updated input fields 

### ISSUE THREAD

**Issue by thedoublejay** [BirthdayResearch/defichain-wallet#943]
#### What would you like to be added:
@jtlntno-cake Can we also update the restore wallet screen so it can use the new input text component?
![image](https://user-images.githubusercontent.com/25013382/135005778-4120b51c-9cee-42a9-901e-9218eb67303c.png)

#### Acceptance Criteria:

- [ ] Current input fields for Restore page are too small, would be great to have the same font size as the new input field
- [ ] Clicking on Enter moves to next line
- [ ] Last element click will submit form
- [ ] Input should be lower case
- [ ] Input line validation (required and lower case only)
- [ ] Trim whitespace

**Comment by jtlntno-cake** [comment]
Right @thedoublejay will work on this screen

**Comment by jtlntno-cake** [comment]
Please [see this link](https://www.figma.com/file/SDIpZciuxJlUf4xf8yheiY/Mobile-Light-Wallet?node-id=1973%3A33282) for an updated design of this screen
